# Generated by Django 3.2 on 2021-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
