# Generated by Django 3.2 on 2021-04-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0002_auto_20210417_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('level', models.CharField(choices=[('FR', 'Freshman'), ('JR', 'Junior'), ('ML', 'Middle'), ('SR', 'Senior')], default='JR', max_length=2, verbose_name='Уровень')),
                ('rating', models.FloatField()),
                ('email', models.EmailField(max_length=20, verbose_name='Эл. почта')),
                ('registrDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'разработчик',
                'verbose_name_plural': 'разработчики',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('startDate', models.DateTimeField(auto_now_add=True, verbose_name='Время получения задания')),
                ('complexity', models.IntegerField(choices=[(0, 'Easy'), (1, 'Average'), (2, 'Hard')])),
                ('developers', models.ManyToManyField(to='bd_app.Developers')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
