# Generated by Django 3.2 on 2021-04-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0003_auto_20210417_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Эл. почта'),
        ),
    ]
