# Generated by Django 3.2 on 2021-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0004_alter_developers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='complexity',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Average'), (2, 'Hard')], default=1, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='developers',
            field=models.ManyToManyField(to='bd_app.Developers', verbose_name='Разработчики'),
        ),
    ]
