# Generated by Django 3.2 on 2021-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0005_auto_20210417_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='developers',
            field=models.ManyToManyField(related_name='tasks', to='bd_app.Developers', verbose_name='Разработчики'),
        ),
    ]
